default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: furima_42223_development

test:
  <<: *default
  database: furima_42223_test

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || 'furima_42223_production' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'furima_42223' %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>