default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: furima_42223_development

test:
  <<: *default
  database: furima_42223_test

production:
  <<: *default
  database: furima_42223_production
  username: furima_42223
  password: <%= ENV["FURIMA_42223_DATABASE_PASSWORD"] %>
